### ISSUE TITLE
DFU mode from Marlin not working

### ISSUE THREAD

**Issue by Firnthon** [markrossington/sidewinder-x2-marlin#24]
There is a better way to access the DFU mode without touching the mainboard, follow this guide:

https://blog.freakydu.de/posts/2022-09-30-flash_marlin_sidewinderx2/

**Comment by markrossington** [comment]
This looks to be the same way described in my file here https://github.com/markrossington/sidewinder-x2-marlin/blob/main/flashing.md

**Comment by markrossington** [comment]
That is: use a serial terminal to send `m997`

**Comment by Firnthon** [comment]
It's describing errors that you can ignore and Devices that you need to
check. Plus in my case cube soft was requires as normal drivers didn't
allow me upload to firmware.

śr., 19 lip 2023, 23:50 użytkownik markrossington ***@***.***>
napisał:

**Comment by markrossington** [comment]
Added his guide, thanks for your contribution
