### ISSUE TITLE
Compile to .hex for STM32Programmer

### ISSUE THREAD

**Issue by aweussom** [markrossington/sidewinder-x2-marlin#26]
My SWX2 turns up in Device Manager as STM32Bootloader after M997.

I need the firmware as a .hex file to program using STM32 Programmer - how can I generate that?

**Comment by aweussom** [comment]
I caved in an put a jumper on boot/3.3v and flashed .bin using dfu-util.exe.

**Comment by markrossington** [comment]
You could have used dfu-util for the first device I believe.

**Comment by aweussom** [comment]
> You could have used dfu-util for the first device I believe. (In stm32bootloader mode)

Sorry, no. 
dfu-util -l 

did not list the STM when it was in STM32Bootloader mode.
Needed to jumper it to "boot" before it turned up.

**Comment by aweussom** [comment]
Other than that, excellent work!

The flash script does not work on Windows, but you probably knew that :-)
