### ISSUE TITLE
Filament runout sensor not working with octoprint

### ISSUE THREAD

**Issue by jordicli** [markrossington/sidewinder-x2-marlin#27]
It seems that with this firmware the filament runout sensor is not working printing with octorpint. 
Do I have to take any adittional step to get it working with octoprint?

**Comment by markrossington** [comment]
Yes, the filament run out sensor is connected to the TFT(screen) and so only that can detect if you've run out. Unfortunately the screen can not inform octoprint of this. 

You can remap an alternate input into the main board for filament run out and I may detail how to do this in future. 

Sorry I can't add much detail right now. I'm not at my main machine.
